Resources:
  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: t_reportes
      AttributeDefinitions:
      - AttributeName: id_reporte
        AttributeType: S
      KeySchema:
      - AttributeName: id_reporte
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  WSConnections:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: t_connections
      AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TUsuarios:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: t_usuarios
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TLugares:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: t_lugares
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
